language: node_js
node_js:
  - "12"
dist: trusty
env:
  - NODE_ENV=ci PORT=3000
cache:
  - node_modules
  - client/node_modules
install:
  - npm install
  - npm run build
script:
  - nohup npm run start &
  - sleep 3
  - npm run test